version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api_network
    hostname: api.local
    ports:
      - 8000:8000
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8000"]
      interval: 3s
      timeout: 1s
      retries: 20

networks:
  api_network:
    driver: bridge